package com.openmemind.ai.memory.core.retrieval.tier;

import com.openmemind.ai.memory.core.retrieval.scoring.ScoredResult;
import java.util.List;

/**
 * Single-layer retrieval result
 *
 * <p>Each Tier Retriever returns this result, containing scoring results and scopeHints used to constrain the search range of the next layer
 *
 * @param results           Scoring results retrieved at this layer
 * @param scopeHints        Range constraints passed to the next layer (Tier1→categories, Tier2→rawDataIds)
 * @param expandedInsights  Context and leaf insights generated by tree expansion (not search hits, but associated through tree relationships)
 */
public record TierResult(
        List<ScoredResult> results,
        List<String> scopeHints,
        List<InsightTreeExpander.ExpandedInsight> expandedInsights) {

    /** Backward compatible 2-parameter constructor */
    public TierResult(List<ScoredResult> results, List<String> scopeHints) {
        this(results, scopeHints, List.of());
    }

    /** Empty result */
    public static TierResult empty() {
        return new TierResult(List.of(), List.of(), List.of());
    }
}
