/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRetrieveRouteImport } from './routes/_app/retrieve'
import { Route as AppRawDataRouteImport } from './routes/_app/raw-data'
import { Route as AppMemoryThreadsRouteImport } from './routes/_app/memory-threads'
import { Route as AppItemsRouteImport } from './routes/_app/items'
import { Route as AppItemGraphRouteImport } from './routes/_app/item-graph'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppConfigRouteImport } from './routes/_app/config'
import { Route as AppBuffersRouteImport } from './routes/_app/buffers'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRetrieveRoute = AppRetrieveRouteImport.update({
  id: '/retrieve',
  path: '/retrieve',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRawDataRoute = AppRawDataRouteImport.update({
  id: '/raw-data',
  path: '/raw-data',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMemoryThreadsRoute = AppMemoryThreadsRouteImport.update({
  id: '/memory-threads',
  path: '/memory-threads',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppItemGraphRoute = AppItemGraphRouteImport.update({
  id: '/item-graph',
  path: '/item-graph',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBuffersRoute = AppBuffersRouteImport.update({
  id: '/buffers',
  path: '/buffers',
  getParentRoute: () => AppRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/buffers': typeof AppBuffersRoute
  '/config': typeof AppConfigRoute
  '/insights': typeof AppInsightsRoute
  '/item-graph': typeof AppItemGraphRoute
  '/items': typeof AppItemsRoute
  '/memory-threads': typeof AppMemoryThreadsRoute
  '/raw-data': typeof AppRawDataRoute
  '/retrieve': typeof AppRetrieveRoute
}
export interface FileRoutesByTo {
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/buffers': typeof AppBuffersRoute
  '/config': typeof AppConfigRoute
  '/insights': typeof AppInsightsRoute
  '/item-graph': typeof AppItemGraphRoute
  '/items': typeof AppItemsRoute
  '/memory-threads': typeof AppMemoryThreadsRoute
  '/raw-data': typeof AppRawDataRoute
  '/retrieve': typeof AppRetrieveRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_app/buffers': typeof AppBuffersRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/item-graph': typeof AppItemGraphRoute
  '/_app/items': typeof AppItemsRoute
  '/_app/memory-threads': typeof AppMemoryThreadsRoute
  '/_app/raw-data': typeof AppRawDataRoute
  '/_app/retrieve': typeof AppRetrieveRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/500'
    | '/503'
    | '/buffers'
    | '/config'
    | '/insights'
    | '/item-graph'
    | '/items'
    | '/memory-threads'
    | '/raw-data'
    | '/retrieve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/500'
    | '/503'
    | '/buffers'
    | '/config'
    | '/insights'
    | '/item-graph'
    | '/items'
    | '/memory-threads'
    | '/raw-data'
    | '/retrieve'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_app/buffers'
    | '/_app/config'
    | '/_app/insights'
    | '/_app/item-graph'
    | '/_app/items'
    | '/_app/memory-threads'
    | '/_app/raw-data'
    | '/_app/retrieve'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/retrieve': {
      id: '/_app/retrieve'
      path: '/retrieve'
      fullPath: '/retrieve'
      preLoaderRoute: typeof AppRetrieveRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/raw-data': {
      id: '/_app/raw-data'
      path: '/raw-data'
      fullPath: '/raw-data'
      preLoaderRoute: typeof AppRawDataRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/memory-threads': {
      id: '/_app/memory-threads'
      path: '/memory-threads'
      fullPath: '/memory-threads'
      preLoaderRoute: typeof AppMemoryThreadsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/items': {
      id: '/_app/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/item-graph': {
      id: '/_app/item-graph'
      path: '/item-graph'
      fullPath: '/item-graph'
      preLoaderRoute: typeof AppItemGraphRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/buffers': {
      id: '/_app/buffers'
      path: '/buffers'
      fullPath: '/buffers'
      preLoaderRoute: typeof AppBuffersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppBuffersRoute: typeof AppBuffersRoute
  AppConfigRoute: typeof AppConfigRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppItemGraphRoute: typeof AppItemGraphRoute
  AppItemsRoute: typeof AppItemsRoute
  AppMemoryThreadsRoute: typeof AppMemoryThreadsRoute
  AppRawDataRoute: typeof AppRawDataRoute
  AppRetrieveRoute: typeof AppRetrieveRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBuffersRoute: AppBuffersRoute,
  AppConfigRoute: AppConfigRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppItemGraphRoute: AppItemGraphRoute,
  AppItemsRoute: AppItemsRoute,
  AppMemoryThreadsRoute: AppMemoryThreadsRoute,
  AppRawDataRoute: AppRawDataRoute,
  AppRetrieveRoute: AppRetrieveRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
