--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

ALTER TABLE memory_item
    ADD COLUMN extraction_batch_id VARCHAR(64);
CREATE INDEX idx_memory_item_batch ON memory_item(memory_id, extraction_batch_id);

ALTER TABLE memory_item_link
    ADD COLUMN relation_code VARCHAR(64),
    ADD COLUMN evidence_source VARCHAR(64);

CREATE TABLE IF NOT EXISTS memory_item_graph_batch (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   VARCHAR(64)  NOT NULL,
    agent_id                  VARCHAR(64)  NOT NULL,
    memory_id                 VARCHAR(200) NOT NULL,
    extraction_batch_id       VARCHAR(64)  NOT NULL,
    state                     VARCHAR(32)  NOT NULL,
    error_message             VARCHAR(1024),
    retry_promotion_supported BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at                TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted                   BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_item_graph_batch_identity
    ON memory_item_graph_batch(memory_id, extraction_batch_id);

CREATE TABLE IF NOT EXISTS memory_graph_alias_batch_receipt (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             VARCHAR(64)  NOT NULL,
    agent_id            VARCHAR(64)  NOT NULL,
    memory_id           VARCHAR(200) NOT NULL,
    entity_key          VARCHAR(255) NOT NULL,
    entity_type         VARCHAR(32)  NOT NULL,
    normalized_alias    VARCHAR(255) NOT NULL,
    extraction_batch_id VARCHAR(64)  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted             BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_graph_alias_batch_receipt_identity
    ON memory_graph_alias_batch_receipt(
        memory_id,
        entity_key,
        entity_type,
        normalized_alias,
        extraction_batch_id
    );
