--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE IF NOT EXISTS memory_raw_data (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id            VARCHAR(64)              NOT NULL,
    user_id           VARCHAR(64)              NOT NULL,
    agent_id          VARCHAR(64)              NOT NULL,
    memory_id         VARCHAR(200)             NOT NULL,
    type              VARCHAR(32)              NOT NULL,
    content_id        VARCHAR(200),
    segment           JSONB,
    caption           TEXT,
    caption_vector_id VARCHAR(200),
    metadata          JSONB,
    start_time        TIMESTAMPTZ,
    end_time          TIMESTAMPTZ,
    created_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_raw_data_biz_id ON memory_raw_data(user_id, agent_id, biz_id);
CREATE INDEX IF NOT EXISTS idx_raw_data_content_id ON memory_raw_data(user_id, agent_id, content_id);
CREATE INDEX IF NOT EXISTS idx_raw_data_memory_id ON memory_raw_data(user_id, agent_id);

CREATE TABLE IF NOT EXISTS memory_item (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id        BIGINT                   NOT NULL,
    user_id       VARCHAR(64)              NOT NULL,
    agent_id      VARCHAR(64)              NOT NULL,
    memory_id     VARCHAR(200)             NOT NULL,
    content       TEXT                     NOT NULL,
    scope         VARCHAR(16)              NOT NULL,
    category      VARCHAR(64),
    vector_id     VARCHAR(200),
    raw_data_id   VARCHAR(64),
    content_hash  VARCHAR(128),
    occurred_at   TIMESTAMPTZ,
    observed_at   TIMESTAMPTZ,
    type          VARCHAR(16)              NOT NULL DEFAULT 'FACT',
    raw_data_type VARCHAR(32)              NOT NULL DEFAULT 'CONVERSATION',
    metadata      JSONB,
    created_at    TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_item_biz_id ON memory_item(user_id, agent_id, biz_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_item_content_hash ON memory_item(user_id, agent_id, content_hash);
CREATE INDEX IF NOT EXISTS idx_item_memory_id ON memory_item(user_id, agent_id);
CREATE INDEX IF NOT EXISTS idx_item_raw_data_id ON memory_item(user_id, agent_id, raw_data_id);
CREATE INDEX IF NOT EXISTS idx_item_type ON memory_item(user_id, agent_id, type);
CREATE INDEX IF NOT EXISTS idx_item_category ON memory_item(memory_id, category);
CREATE INDEX IF NOT EXISTS idx_item_scope_category ON memory_item(memory_id, scope, category);

CREATE TABLE IF NOT EXISTS memory_insight_type (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id                BIGINT,
    name                  VARCHAR(128)             NOT NULL,
    description           TEXT,
    description_vector_id VARCHAR(200),
    categories            JSONB,
    target_tokens         INT                      NOT NULL DEFAULT 0,
    analysis_mode         VARCHAR(32)              DEFAULT 'BRANCH',
    scope                 VARCHAR(32),
    tree_config           JSONB,
    last_updated_at       TIMESTAMPTZ,
    created_at            TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_insight_type_name ON memory_insight_type(name);

CREATE TABLE IF NOT EXISTS memory_insight (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id            BIGINT                   NOT NULL,
    user_id           VARCHAR(64)              NOT NULL,
    agent_id          VARCHAR(64)              NOT NULL,
    memory_id         VARCHAR(200)             NOT NULL,
    type              VARCHAR(128)             NOT NULL,
    scope             VARCHAR(16)              NOT NULL,
    name              VARCHAR(256),
    categories        JSONB,
    content           TEXT,
    points            JSONB,
    group_name        VARCHAR(64),
    confidence        REAL                     DEFAULT 0,
    last_reasoned_at  TIMESTAMPTZ,
    summary_embedding JSONB,
    tier              VARCHAR(16),
    parent_insight_id BIGINT,
    child_insight_ids JSONB,
    version           INT                      NOT NULL DEFAULT 1,
    created_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_insight_biz_id ON memory_insight(user_id, agent_id, biz_id);
CREATE INDEX IF NOT EXISTS idx_insight_memory_id ON memory_insight(user_id, agent_id);
CREATE INDEX IF NOT EXISTS idx_insight_type ON memory_insight(user_id, agent_id, type);
CREATE INDEX IF NOT EXISTS idx_insight_parent ON memory_insight(user_id, agent_id, parent_insight_id);
CREATE INDEX IF NOT EXISTS idx_insight_tier ON memory_insight(user_id, agent_id, tier);
CREATE INDEX IF NOT EXISTS idx_insight_tier_group ON memory_insight(user_id, agent_id, type, tier, group_name);

CREATE TABLE IF NOT EXISTS memory_conversation_buffer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(128)             NOT NULL,
    user_id    VARCHAR(64)              NOT NULL,
    agent_id   VARCHAR(64)              NOT NULL,
    memory_id  VARCHAR(200)             NOT NULL,
    role       VARCHAR(16)              NOT NULL,
    content    TEXT                     NOT NULL,
    user_name  VARCHAR(64),
    timestamp  TIMESTAMPTZ,
    extracted  BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted    BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_buf_pending
    ON memory_conversation_buffer(session_id, extracted, deleted, id);
CREATE INDEX IF NOT EXISTS idx_buf_recent ON memory_conversation_buffer(session_id, deleted, id);
CREATE INDEX IF NOT EXISTS idx_buf_memory_id ON memory_conversation_buffer(user_id, agent_id, deleted, id);

CREATE TABLE IF NOT EXISTS memory_insight_buffer (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           VARCHAR(64)              NOT NULL,
    agent_id          VARCHAR(64)              NOT NULL,
    memory_id         VARCHAR(200)             NOT NULL,
    insight_type_name VARCHAR(128)             NOT NULL,
    item_id           BIGINT                   NOT NULL,
    group_name        VARCHAR(64),
    built             BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_insight_buffer
    ON memory_insight_buffer(user_id, agent_id, insight_type_name, item_id);
CREATE INDEX IF NOT EXISTS idx_insight_buf_type
    ON memory_insight_buffer(user_id, agent_id, insight_type_name);
CREATE INDEX IF NOT EXISTS idx_insight_buf_group
    ON memory_insight_buffer(user_id, agent_id, insight_type_name, group_name);
