--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE IF NOT EXISTS memory_graph_entity (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      VARCHAR(64)  NOT NULL,
    agent_id     VARCHAR(64)  NOT NULL,
    memory_id    VARCHAR(200) NOT NULL,
    entity_key   VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    entity_type  VARCHAR(32)  NOT NULL,
    metadata     JSONB,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_graph_entity_identity
    ON memory_graph_entity(memory_id, entity_key);

CREATE TABLE IF NOT EXISTS memory_item_entity_mention (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(64)  NOT NULL,
    agent_id   VARCHAR(64)  NOT NULL,
    memory_id  VARCHAR(200) NOT NULL,
    item_id    BIGINT       NOT NULL,
    entity_key VARCHAR(255) NOT NULL,
    confidence REAL,
    metadata   JSONB,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted    BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_item_entity_mention_identity
    ON memory_item_entity_mention(memory_id, item_id, entity_key);
CREATE INDEX IF NOT EXISTS idx_item_entity_mention_item
    ON memory_item_entity_mention(memory_id, item_id);
CREATE INDEX IF NOT EXISTS idx_item_entity_mention_entity_key
    ON memory_item_entity_mention(memory_id, entity_key);

CREATE TABLE IF NOT EXISTS memory_item_link (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        VARCHAR(64)  NOT NULL,
    agent_id       VARCHAR(64)  NOT NULL,
    memory_id      VARCHAR(200) NOT NULL,
    source_item_id BIGINT       NOT NULL,
    target_item_id BIGINT       NOT NULL,
    link_type      VARCHAR(32)  NOT NULL,
    strength       DOUBLE PRECISION,
    metadata       JSONB,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted        BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_item_link_identity
    ON memory_item_link(memory_id, source_item_id, target_item_id, link_type);
CREATE INDEX IF NOT EXISTS idx_item_link_source_type
    ON memory_item_link(memory_id, source_item_id, link_type);
CREATE INDEX IF NOT EXISTS idx_item_link_target_type
    ON memory_item_link(memory_id, target_item_id, link_type);

CREATE TABLE IF NOT EXISTS memory_entity_cooccurrence (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            VARCHAR(64)  NOT NULL,
    agent_id           VARCHAR(64)  NOT NULL,
    memory_id          VARCHAR(200) NOT NULL,
    left_entity_key    VARCHAR(255) NOT NULL,
    right_entity_key   VARCHAR(255) NOT NULL,
    cooccurrence_count INTEGER      NOT NULL,
    metadata           JSONB,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_entity_cooccurrence_identity
    ON memory_entity_cooccurrence(memory_id, left_entity_key, right_entity_key);
