--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE IF NOT EXISTS memory_graph_entity_alias (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            VARCHAR(64)  NOT NULL,
    agent_id           VARCHAR(64)  NOT NULL,
    memory_id          VARCHAR(200) NOT NULL,
    entity_key         VARCHAR(255) NOT NULL,
    entity_type        VARCHAR(32)  NOT NULL,
    normalized_alias   VARCHAR(255) NOT NULL,
    evidence_count     INTEGER      NOT NULL,
    metadata           JSONB,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_graph_entity_alias_identity
    ON memory_graph_entity_alias(memory_id, entity_type, entity_key, normalized_alias);
CREATE INDEX IF NOT EXISTS idx_graph_entity_alias_lookup
    ON memory_graph_entity_alias(memory_id, entity_type, normalized_alias);
